version: '1'
services:
  ros_ws1:
    image: hph/ros-desktop:melodic
    # cpus: 1.0
    volumes: 
      - ./.bashrc:/home/ubuntu/.bashrc
      - /Users/hph/Codes/VINS-Fusion:/home/ubuntu/ros_ws/src/VINS-Fusion
      - /Users/hph/Data:/var/data
    ports:
      -  "6080:80"
      -  "2222:22"
    tty: true

    
